// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaVvXlhq-ePid5rD0fjQ1JOFF7uFgnWYI',
    appId: '1:651909603814:android:40037164edddbac098f627',
    messagingSenderId: '651909603814',
    projectId: 'flash-chat-1ea83',
    storageBucket: 'flash-chat-1ea83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg7Cn8dSOLM4AOngZJsjQ3K8duq_hafQQ',
    appId: '1:651909603814:ios:9e9c9e84778dac4898f627',
    messagingSenderId: '651909603814',
    projectId: 'flash-chat-1ea83',
    storageBucket: 'flash-chat-1ea83.appspot.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg7Cn8dSOLM4AOngZJsjQ3K8duq_hafQQ',
    appId: '1:651909603814:ios:770d06c5511c579498f627',
    messagingSenderId: '651909603814',
    projectId: 'flash-chat-1ea83',
    storageBucket: 'flash-chat-1ea83.appspot.com',
    iosBundleId: 'com.flashchat.app',
  );
}
